version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - gocritic
    - revive
    - prealloc

  exclusions:
    rules:
      - linters: [revive]
        text: "exported: "
      - linters: [revive]
        text: "package-comments:"

formatters:
  enable:
    - gofumpt
